services:
    TBoileau\FormHandlerBundle\Factory\FormManagerFactoryInterface: '@tboileau.form_handler.manager_factory'
    tboileau.form_handler.manager_factory:
        class: TBoileau\FormHandlerBundle\Factory\FormManagerFactory
        arguments:
            - '@form.factory'
            -
